### ISSUE TITLE
Rename `*.ql` files to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [ThomasG77/30DayMapChallenge#2]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all `*.ql` files in this repo to `*.overpassql`  for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by FloEdelmann** [comment]
@ThomasG77 Would a PR be accepted?

**Comment by ThomasG77** [comment]
No need: done e.g https://github.com/ThomasG77/30DayMapChallenge/commit/4fb2bfd08c67fd92151e7b91132b795e95f0b7f7

**Comment by FloEdelmann** [comment]
Even better. Thank you!
